# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - jpellwebapp

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://github.com/jimpson1/cancodefinalproject/blob/master/templates/testweb.html/
        username: ${{ secrets.AzureAppService_ContainerUsername_73e59a2476da4022abea1ccc4b29e38e }}
        password: ${{ secrets.AzureAppService_ContainerPassword_5b7e40cbfbc14cebb0e1edc53346913c }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: github.com/jimpson1/cancodefinalproject/blob/master/templates/testweb.html/${{ secrets.AzureAppService_ContainerUsername_73e59a2476da4022abea1ccc4b29e38e }}/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'jpellwebapp'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_acdd891c5b2a4b7cb3358db42bb33039 }}
        images: 'github.com/jimpson1/cancodefinalproject/blob/master/templates/testweb.html/${{ secrets.AzureAppService_ContainerUsername_73e59a2476da4022abea1ccc4b29e38e }}/appsvc/staticsite:${{ github.sha }}'